default:
  tags:
    - java
    - selfhosted

variables:
  FORTIFY_BUILD_ID: "eightball"
  SSC_APP_NAME: "eightball"
  SSC_APP_VER_NAME: "1.0"

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
      when: never  # Prevent pipeline run for push event
    - when: always # Run pipeline for all other cases

stages:
  - build
  - fortify:translate
  - fortify:scan
  - fortify:upload

.build:
  stage: build
  image: eclipse-temurin:8-jdk
  script:
    - javac EightBall.java
  artifacts:
    paths:
      - "*.class"
    expire_in: 1 day

fortify-localTranslate:
  stage: fortify:translate
  script: 
    - sourceanalyzer -b "$FORTIFY_BUILD_ID" -project-root ".fortify" -debug -verbose -jdk 8 EightBall.java
  artifacts:
    paths:
      - ".fortify"
    expire_in: 2 hours

fortify-localScan:
  stage: fortify:scan
  script: 
    - fortifyupdate -url "$FORTIFY_UPDATE_URL" -acceptKey -acceptSSLCertificate
    - > 
      sourceanalyzer -b "$FORTIFY_BUILD_ID" 
      -project-root ".fortify" 
      -debug -verbose 
      -scan -f "$FORTIFY_BUILD_ID.fpr"
  artifacts:
    paths:
      - ".fortify"
      - "*.fpr"
    expire_in: 1 week

fortify-upload:
  stage: fortify:upload
  script: 
    - >
      fortifyclient -url "$SSC_URL" -authtoken "$SSC_TOKEN" 
      uploadFPR -file "$FORTIFY_BUILD_ID.fpr" 
      -project "$SSC_APP_NAME" -version "$SSC_APP_VER_NAME"