name: "Fortify SAST"

on: 
  workflow_dispatch:
env:
  FOD_RELEASE_ID: "1018443"
  FOD_UPLOADER_NOTES: "Triggered by GitHub"

jobs:
  sast:
    # https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2404-Readme.md
    runs-on: ubuntu-24.04
    steps:
      - name: Check out source code
        uses: actions/checkout@v4

      # Tools Definition in
      # https://github.com/fortify/github-action/blob/main/setup/src/constants.ts not updated
      # 
      # Able override if updated in 
      # https://github.com/fortify/tool-definitions/releases/download/v1/tool-definitions.yaml.zip
      # - name: FoD SAST Assessment
      #   uses: fortify/github-action@v1
      #   with:
      #     sast-scan: true
      #   env:
      #     FOD_URL: ${{vars.FOD_PORTAL_URL}}
      #     FOD_CLIENT_ID: ${{secrets.FOD_API_KEY}}
      #     FOD_CLIENT_SECRET: ${{secrets.FOD_API_SECRET}}
      #     FOD_RELEASE: $FOD_RELEASE_ID
      #     # FOD_RELEASE: MyApp:MyRelease
      #     # EXTRA_PACKAGE_OPTS: -oss
      #     # DO_WAIT: true
      #     # DO_EXPORT: true
      #     # TOOL_DEFINITIONS: https://github.com/fortify/tool-definitions/releases/tag/v1/tool-definitions.yaml.zip

      # Check list of version from:
      # https://github.com/fortify/tool-definitions/tree/main/v1
      - name: FoD Tools Setup
        uses: fortify/github-action/setup@v1
        with:
          sc-client: 24.2.0
          fod-uploader: latest
          vuln-exporter: latest
          
      - name: Set SCANCENTRAL_JAVA_HOME
        run: |
          echo "SCANCENTRAL_JAVA_HOME=${JAVA_HOME_21_X64}" >> $GITHUB_ENV

      # - name: Check Env Var
      #   run: env

      - name: Package
        run: scancentral package $PACKAGE_OPTS -o package.zip

      - name: Upload Package
        uses: actions/upload-artifact@v4
        with:
          name: Scancentral Package
          path: package.zip
          retention-days: 7

      - name: Upload 
        run: >
          FoDUpload -apiCredentials "${{secrets.FOD_API_KEY}}" "${{secrets.FOD_API_SECRET}}" 
          -releaseId "$FOD_RELEASE_ID" 
          -portalurl "${{vars.FOD_PORTAL_URL}}" -apiurl "${{vars.FOD_API_URL}}" 
          -zipLocation package.zip 
          -technologyStackId 7 -languageLevelId 12 
          -assessmentTypeId 274 
          -entitlementPreferenceType SubscriptionOnly 
          -auditPreferenceId Automated 
          -inProgressScanActionType Queue 
          -notes "$FOD_UPLOADER_NOTES"