name: "Fortify SAST"

on: 
  workflow_dispatch:
env:
  FORTIFY_BUILD_ID: "eightball"
  SSC_APP_NAME: "eightball"
  SSC_APP_VER_NAME: "scsast_remotescan"

jobs:
  sast:
    runs-on: self-hosted
    steps:
      - name: Check out source code
        uses: actions/checkout@v4

      - name: Fortify SAST Assessment
        run: |
          sourceanalyzer -b "${{env.FORTIFY_BUILD_ID}}" -project-root ".fortify" -debug -verbose -logfile trans.log -jdk 8 EightBall.java
          scancentral -sscurl "${{secrets.SSC_URL}}" -ssctoken "${{secrets.SSC_TOKEN}}" start -upload -application "${{env.SSC_APP_NAME}}" -version "${{env.SSC_APP_VER_NAME}}" -projroot ".fortify" -uptoken "${{secrets.SSC_TOKEN}}" -b "${{env.FORTIFY_BUILD_ID}}" -scan 
      - name: Save Fortify Logs
        uses: actions/upload-artifact@v4
        if: always()
        with:
            name: fortify-logs
            path: |
              *.log
              .fortify
            retention-days: 7