name: "Fortify SAST"

on: 
  workflow_dispatch:
env:
  FORTIFY_BUILD_ID: "eightball"
  SSC_APP_NAME: "eightball"
  SSC_APP_VER_NAME: "1.0"

jobs:
  sast:
    runs-on: self-hosted
    steps:
      - name: Check out source code
        uses: actions/checkout@v4

      - name: Fortify SAST Assessment
        run: |
          fortifyupdate -url "${{secrets.SSC_URL}}" -acceptKey -acceptSSLCertificate 
          sourceanalyzer -b "${{env.FORTIFY_BUILD_ID}}" -project-root ".fortify" -debug -verbose -logfile trans.log -jdk 8 EightBall.java
          sourceanalyzer -b "${{env.FORTIFY_BUILD_ID}}" -project-root ".fortify" -debug -verbose -logfile scan.log -scan -f "${{env.FORTIFY_BUILD_ID}}.fpr" 
          fortifyclient -url "${{secrets.SSC_URL}}" -authtoken "${{secrets.SSC_TOKEN}}" uploadFPR -file "${{env.FORTIFY_BUILD_ID}}.fpr" -project "${{env.SSC_APP_NAME}}" -version "${{env.SSC_APP_VER_NAME}}"
      
      - name: Save Fortify Logs
        uses: actions/upload-artifact@v4
        if: always()
        with:
            name: fortify-logs
            path: |
              *.log
              *.fpr
            retention-days: 7
