name: "Fortify SAST"

on: 
  workflow_dispatch:
env:
  FORTIFY_BUILD_ID: "eightball"
  SSC_APP_NAME: "eightball"
  SSC_APP_VER_NAME: "1.0"

jobs:
  sast:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v4